### ISSUE TITLE
Discussion: Code/work pipeline 

### ISSUE THREAD

**Issue by EkkuJ** [lacabra/proco-map-app#21]

**Comment by EkkuJ** [comment]
I think it would clarify the development work for all of us if we based our PR's against the development-branch. Now the dev-branch is sometimes lagging behind the changes made to master. The versioning-history becomes a bit mystical when we we start to merge the branches together.

My proposal would be to base all PRs against the dev-branch. Then, as we want to deploy the changes and [https://develop.projectconnect.app/](https://develop.projectconnect.app/) has no bugs, we just do a dev -> master merge. So generally to never merge changes to master directly, unless it's something critical.

What are your thoughts? @lacabra @CallaJune

**Comment by CallaJune** [comment]
@EkkuJ I would defer to @lacabra on workflow, but this makes a lot of sense. It's common practice to have a staging branch (such as `dev-branch`) to merge and test thoroughly once over before merging to production. I wasn't aware of that flow (using `dev-branch` as a staging branch) and so it may thanks to me that the workflow has been disrupted. I'm happy to merge changes to `dev-branch` from hereon out.

**Comment by lacabra** [comment]
@EkkuJ Thanks for brining this up. I agree that what you propose makes the most sense. Having said this, and being fully aware of having the `develop` branch as the staging branch, my choice of current work flow is intentional because there are some features that @CallaJune has been working on that we needed to show to other stakeholders in production (pushed to `master`), but the work on `develop` that contains the user management is not ready to be put in production, so I have been consciously bypassing the normal workflow to accommodate for this unusual situation.

Moving forward the priority is certainly to bring the `develop` branch to a point where we can consistently merge it to `master` as new features are fully tested. Until then, I take full responsibility for the additional burden of keeping branches in sync.

**Comment by EkkuJ** [comment]
@lacabra I see, this makes sense as well.
