### ISSUE TITLE
Button size—'Yes' 'No' 'Maybe'

### ISSUE THREAD

**Issue by upretiprateek** [lacabra/proco-map-app#92]
Right now the button sizes for the 3 options ('Yes' 'No' 'Maybe') feels small, especially while playing the game in mobile site.
Can the sizes be increased as per Zeplin: https://zpl.io/2vE7pmY

Ideally if the 3 buttons can span across the width of the map image, with paddings between each other.

**Comment by rachita19082** [comment]
@lacabra I would like to work on this issue. Please assign it to me.

**Comment by rachita19082** [comment]
@lacabra Thank you for assigning this issue to me. I am unable to access the [Zeplin link](https://zpl.io/2vE7pmY). It displays a message "You are not invited to the project". Could you please help me out with accessing it or provide a bit more information on this issue. 
Also the [project app link](https://projectconnect.world/game) seems to be broken. I will start with cloning this repository and then running the project.

**Comment by lacabra** [comment]
@rachita19082 Thanks for pointing out the broken link. The main website was upgraded earlier this week, when the link broke. Use this one instead https://game.projectconnect.world (I've updated the link on the repo description; and yes, you are welcome to play the game 🙃 ). I'm working on the Zeplin link...

**Comment by lacabra** [comment]
Zeplin screenshots:

This is what the distribution and relative size of the buttons should look like (don't mind the grey color of the Next button at the bottom): 

![Screen Shot 2021-04-23 at 1 24 13 PM](https://user-images.githubusercontent.com/6098973/115920321-46a05000-a437-11eb-9e99-7d3ea9202918.png)

Here's some specs about sizes, but bear in mind that in Zeplin they are set in absolute terms, and in order to be responsive, they have to be set in relative units or percentages:

![Screen Shot 2021-04-23 at 1 26 10 PM](https://user-images.githubusercontent.com/6098973/115920585-a0a11580-a437-11eb-99e8-38051bf761f9.png)

**Comment by rachita19082** [comment]
> Here's some specs about sizes, but bear in mind that in Zeplin they are set in absolute terms, and in order to be responsive, they have to be set in relative units or percentages:
Thank you, I will start working on it and get in touch if I have any further doubts.

**Comment by rachita19082** [comment]
@lacabra I have made the required change in the code. However, while committing the change, I noticed some modifications in the package-lock.json file even though I did not make any changes. Please let me know what could have caused these changes and if I should keep them or remove them while committing.

**Comment by rachita19082** [comment]
@lacabra I also wanted to know if I should change the border-radius to 18.5 px as given in the Zeplin screenshot and make the button text "Maybe" instead of "Unsure".

**Comment by lacabra** [comment]
Thanks @rachita19082:
* Do not worry about changes to `package-lock.json` and commit your newer version to the repo. It is probably due to the fact that you installed dependencies more recently (`npm i`), and npm updated some of the underlying dependencies. I would say that is generally good to keep this file up to date.
* Do not change the text from `Unsure`
* Yes, do the changes to the border-radius so that the layout (including buttons) looks as closely as possible as the design provided by @upretiprateek

**Comment by rachita19082** [comment]
@lacabra I have made the required changes in the pull request #97. However it is failing checks, probably due to authorization. Please let me know if I can do something about that. Please review the PR and let me know if anything else is needed.

**Comment by lacabra** [comment]
Thanks @rachita19082, I have approved the deployment, and I will review the pull request later today or tomorrow, thank you

**Comment by rachita19082** [comment]
@lacabra Okay, thank you.
